--Cleaning Internet Sales Data--

SELECT [ProductKey]
      ,[OrderDateKey]
      ,[DueDateKey]
      ,[ShipDateKey]
      ,[CustomerKey]
     --,[PromotionKey]
     --,[CurrencyKey]
     --,[SalesTerritoryKey]
     --,[SalesOrderNumber]
     --,[SalesOrderLineNumber]
     --,[RevisionNumber]
     --,[OrderQuantity]
     --,[UnitPrice]
     --,[ExtendedAmount]
     --,[UnitPriceDiscountPct]
     --,[DiscountAmount]
     --,[ProductStandardCost]
     --,[TotalProductCost]
      ,[SalesAmount]
     --,[TaxAmt]
     --,[Freight]
     --,[CarrierTrackingNumber]
     --,[CustomerPONumber]
     --,[OrderDate]
     --,[DueDate]
     --,[ShipDate]
  FROM [AdventureWorksDW2022].[dbo].[FactInternetSales]
  Where Left ((OrderDateKey),4) >= YEAR(Getdate()) - 2
  Order by
	OrderDateKey ASC